export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  titleColor: '#56C043',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};
export const Color = {
  Red: '#ff0000',
  Yellow: '#F7C245',
  Green: '#75A98E',
  Orange: '#F29D41',
  White: '#ffffff',
  Background: '#1B1D31',
  CardBackground: '#262745',
  FilterBackground: '#33345F',
  OveralRateBackground: '#505295',
  StatusBarMyMedals: '#1C223B',
  StatusBarMedalDetail: '#1D1E36',
  TextDisable: '#8C8D9C',
  TotalOnBadgeBackground: '#515397',
  MedalDescription: '#ACACAC',
  line: '#3F4166',
  MedalDetailBackgroundTop: '#1D1D35',
  MedalDetailBackgroundBottom: '#262745',
  TableHeaderBackground: '#33345F',
  TableRowBackground: '#262745',
  TextButton: '#343434',
  HeaderTable: '#33345F',
  BodyTable: '#262745',
  TextGray: '#ACACAC',
  TextWhite: '#F2F3F4',
  Divider: '#3F4166',
  lightWhite: '#D8D8D8',
  TextBlack: '#1E1E1E',
  Black: '#000000',
  LightGray: '#C3C3C3',
  BorderColor: '#000000',
  BackgroundSelect: '#262745',
  BackgroundTextInput: '#33345F',
  BackgroundItemDropdown: '#3F4166',
  BGModal: '#6b6b6b',
  GrayLight: '#ACACAC',
  ButtonDisable: '#7C6122',
  BackgroundDialog: 'rgba(0, 0, 0, 0.6)',
  BGKeyBoard: '#434343',
  YellowDisable: '#8f690e',
  RedText: '#E12A00',
  TxtDisable: '#7E7E7E',
  BGLetterDetail: '#21224F',
  TxtTitleGray: '#DCDCDC',
};

export default Color;

export const Items = [
  {
    id: 1,
    category: 'product',
    productName: 'Tai nghe chụp tai WH-CH510, pin 25H, mic thoại',
    productPrice: 179,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: true,
    offPercentage: 10,
    productImage: require('../database/images/products/Mi1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/Mi1.png'),
      require('../database/images/products/Mi2.png'),
      require('../database/images/products/Mi3.png'),
    ],
  },
  {
    id: 2,
    category: 'product',
    productName: 'Tai nghe Bluetooth chụp tai chính hãng SD Design PH98',
    productPrice: 149,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 3,
    category: 'accessory',
    productName: 'Tai nghe Airdopes 441',
    productPrice: 199,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: true,
    offPercentage: 18,
    productImage: require('../database/images/accessories/boatairpods1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatairpods1.png'),
      require('../database/images/accessories/boatairpods2.png'),
      require('../database/images/accessories/boatairpods3.png'),
    ],
  },
  {
    id: 4,
    category: 'accessory',
    productName: 'Tai nghe Bassheads 242',
    productPrice: 39,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: false,
    productImage: require('../database/images/accessories/boatbassheads1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatbassheads1.png'),
      require('../database/images/accessories/boatbassheads2.png'),
      require('../database/images/accessories/boatbassheads3.png'),
    ],
  },
  {
    id: 5,
    category: 'accessory',
    productName: 'Tai nghe Rockerz 255 Pro+',
    productPrice: 149,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: false,
    productImage: require('../database/images/accessories/boatrockerz1.png'),
    isAvailable: false,
    productImageList: [
      require('../database/images/accessories/boatrockerz1.png'),
      require('../database/images/accessories/boatrockerz2.png'),
      require('../database/images/accessories/boatrockerz3.png'),
    ],
  },
  {
    id: 6,
    category: 'accessory',
    productName: 'Tai nghe Audio AirBass Propods TWS',
    productPrice: 129,
    description: 'Nghe sướng nhắm, quá đã, quá tuyệt zời!',
    isOff: false,
    productImage: require('../database/images/accessories/boultairbass1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boultairbass1.png'),
      require('../database/images/accessories/boultairbass2.png'),
      require('../database/images/accessories/boultairbass3.png'),
    ],
  },
];
